[package]
name = "sqlite_identifiers"
edition = "2021"
version = "0.0.1"
authors = [
    "Brandon Thomas <bt@brand.io>",
    "Brandon Thomas <echelon@gmail.com>",
]
publish = false

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-build-acceleration"]

[lib]
name = "sqlite_identifiers"
path = "src/lib.rs"

[dependencies]
# Workspace hack (faster compile times)
workspace-build-acceleration.workspace = true

# Serialization
serde.workspace = true
serde_derive.workspace = true

# Token entropy
rand = { version = "0.8.5", features = ["std_rng"] }

[dev-dependencies]
# Enum utilities
strum.workspace = true

# Test serialization
serde_json.workspace = true
