use crate::connection::LocalFilesDbConnection;
use crate::error::LocalFilesDbError;
use crate::queries::local_file_record::LocalFileRecord;

/// Rows the thumbnail worker should (re)try: never generated, failed fewer
/// than `max_attempts` times, or generated by an older generator than
/// `current_generator_version`. Newest first, so fresh downloads win.
pub async fn list_local_files_needing_thumbnails(
  db: &LocalFilesDbConnection,
  max_attempts: i64,
  current_generator_version: i64,
  limit: i64,
) -> Result<Vec<LocalFileRecord>, LocalFilesDbError> {
  let records = sqlx::query_as::<_, LocalFileRecord>(
    r#"
    SELECT * FROM local_files
    WHERE thumbnail_state = 'pending'
       OR (thumbnail_state = 'failed' AND thumbnail_attempts < ?1)
       OR (thumbnail_state = 'generated' AND thumbnail_generator_version < ?2)
    ORDER BY updated_at DESC
    LIMIT ?3
    "#,
  )
      .bind(max_attempts)
      .bind(current_generator_version)
      .bind(limit)
      .fetch_all(db.get_pool())
      .await?;
  Ok(records)
}
