use crate::requests::core_api::fal_request::FalRequest;
use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct NanoBanana2EditImageInput {
  pub prompt: String,

  pub image_urls: Vec<String>,

  /// Eg. "auto", "16:9", "1:1", etc.
  /// Options: auto, 21:9, 16:9, 3:2, 4:3, 5:4, 1:1, 4:5, 3:4, 2:3, 9:16
  /// Default: "auto"
  #[serde(skip_serializing_if = "Option::is_none")]
  pub aspect_ratio: Option<String>,

  /// Eg. "0.5K", "1K", "2K", "4K"
  /// Default: "1K"
  #[serde(skip_serializing_if = "Option::is_none")]
  pub resolution: Option<String>,

  /// 1 - 4
  /// Default: 1
  #[serde(skip_serializing_if = "Option::is_none")]
  pub num_images: Option<u8>,

  /// "jpeg", "png", "webp"
  /// Default: "png"
  #[serde(skip_serializing_if = "Option::is_none")]
  pub output_format: Option<String>,

  #[serde(skip_serializing_if = "Option::is_none")]
  pub seed: Option<u64>,

  /// The safety tolerance level for content moderation.
  /// 1 is the most strict (blocks most content), 6 is the least strict.
  /// Default value: "4"
  ///
  /// Possible enum values: 1, 2, 3, 4, 5, 6
  #[serde(skip_serializing_if = "Option::is_none")]
  pub safety_tolerance: Option<String>,

  /// Experimental parameter to limit the number of generations from each round
  /// of prompting to 1. Set to True to to disregard any instructions in the
  /// prompt regarding the number of images to generate and ignore any
  /// intermediate images generated by the model. This may affect generation
  /// quality.
  ///
  /// Default value: true
  #[serde(skip_serializing_if = "Option::is_none")]
  pub limit_generations: Option<bool>,

  /// Enable web search for the image generation task. This will allow
  /// the model to use the latest information from the web to generate
  /// the image.
  #[serde(skip_serializing_if = "Option::is_none")]
  pub enable_web_search: Option<bool>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct NanoBanana2EditImageFile {
  pub url: String,
  //pub content_type: Option<String>,
  //pub file_name: Option<String>,
  //pub file_size: Option<u64>,
  //pub width: Option<u32>,
  //pub height: Option<u32>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct NanoBanana2EditImageOutput {
  pub images: Vec<NanoBanana2EditImageFile>,
  //pub description: String,
}

pub fn nano_banana_2_edit_image(
  params: NanoBanana2EditImageInput,
) -> FalRequest<NanoBanana2EditImageInput, NanoBanana2EditImageOutput> {
  FalRequest::new("fal-ai/nano-banana-2/edit", params)
}
