use std::error::Error;
use std::fmt::{Display, Formatter};

#[derive(Debug)]
pub enum GrokSpecificApiError {
  /// Grok is detecting and blocking our bot, likely due to new secrets use.
  AutomationBlocked,
  
  /// Too many videos are being generated.
  TooManyVideos,

  /// The image websocket rejected the prompt because the account's image
  /// generation rate limit / quota is exhausted. Carries the full raw error
  /// frame the server sent.
  ImageRateLimitExceeded {
    body: String,
  },

  /// The `x-statsig-id` request signature was missing, stale, or invalid.
  /// Grok gates its chat/generation POST endpoints on a signature that can
  /// only be produced inside a real browser DOM (see [`crate::client::statsig`]),
  /// so this fires when we send a bad one — e.g. the 403 "This page is out of
  /// date. Reload to continue." Carries the HTTP status and full response body
  /// so new/changed notices can be inspected.
  StatsigSignatureRejected {
    status_code: u16,
    body: String,
  },


//  /// Failed to generate a bearer token despite the `200 OK` response.
//  /// This has been generated by sending old/expired session cookies or empty cookies.
//  FailedToGenerateBearerToken,
//
//  /// The endpoint told us we used an invalid JWT.
//  InvalidJwt,
//
//  /// Sora has responded with "sentinel block".
//  /// This usually means we need to refresh our sentinel token.
//  SentinelBlockError,
//
//  /// Sora requires users to set up an account username before they can generate images.
//  /// This requires the user to set up that username.
//  SoraUsernameNotYetCreated,
//
//  /// Sora has responded with "token expired".
//  /// This (probably?) means we need to refresh our JWT bearer token.
//  TokenExpiredError,
//
//  /// We're sending too many tasks to Sora.
//  /// Sora is telling us to cool it.
//  TooManyConcurrentTasks,
//
//  // TODO: Try to make concrete error types for these distinct cases.
//  /// Unauthorized, cookie and/or bearer token expired. We'll need to ask for a refreshed login.
//  ///
//  /// Example message, e.g. from the upload endpoint:
//  ///   {
//  ///     "error": {
//  ///       "message": "Your authentication token has expired. Please try signing in again.",
//  ///       "type": "invalid_request_error",
//  ///       "param": null,
//  ///       "code": "token_expired"
//  ///     }
//  ///   }
//  UnauthorizedCookieOrBearerExpired,
//
//  /// The Sora sentinel token response is missing fields
//  SentinelResponseIsMissingFields {
//    missing_token: bool,
//    missing_turnstile: bool,
//    raw_response: String,
//  },
}

impl Error for GrokSpecificApiError {}

impl Display for GrokSpecificApiError {
  fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
    match self {
      Self::AutomationBlocked => write!(f, "Automation blocked"),
      Self::TooManyVideos => write!(f, "Too many videos are being generated"),
      Self::ImageRateLimitExceeded { body } => write!(f, "Image rate limit / quota exceeded. Raw frame: {}", body),
      Self::StatsigSignatureRejected { status_code, body } => write!(f, "Statsig (x-statsig-id) signature rejected (HTTP {}). Body: {}", status_code, body),

      //Self::FailedToGenerateBearerToken => write!(f, "Failed to generate bearer token. Probably invalid or expired session cookies."),
      //Self::InvalidJwt => write!(f, "Invalid JWT token. Please refresh the token."),
      //Self::SentinelBlockError => write!(f, "Request blocked by Sentinel Token Block. Please refresh the sentinel token."),
      //Self::SoraUsernameNotYetCreated => write!(f, "Sora username not yet created. Please create a username in the Sora app or website."),
      //Self::TokenExpiredError => write!(f, "JWT token has expired. Please refresh the token."),
      //Self::TooManyConcurrentTasks => write!(f, "Too many concurrent tasks. Please wait."),
      //Self::UnauthorizedCookieOrBearerExpired => write!(f, "Unauthorized: cookie and/or bearer token expired"),
      //Self::SentinelResponseIsMissingFields { missing_token: token_missing, missing_turnstile: turnstile_missing, raw_response } => {
      //  write!(f, "Sentinel response is missing fields. token_missing: {}, turnstile_missing: {}. Raw response: {}", token_missing, turnstile_missing, raw_response)
      //},
    }
  }
}
