[package]
name = "enums"
edition = "2018"
version = "0.0.1"
authors = [
    "Brandon Thomas <bt@brand.io>",
    "Brandon Thomas <echelon@gmail.com>",
]
publish = false

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-build-acceleration"]

[lib]
name = "enums"
path = "src/lib.rs"

[dependencies]
# Workspace hack (faster compile times)
workspace-build-acceleration.workspace = true

# Internal
# (None yet)

# Serialization
serde.workspace = true
serde_derive.workspace = true

log.workspace = true

[dev-dependencies]

# Enum utilities
strum.workspace = true

# Test serialization
serde_json.workspace = true
toml.workspace = true
regex.workspace = true
