use crate::configs::video_model_config::VideoModelConfig;
use crate::configs::video_models::strings;
use crate::enums::common_aspect_ratio::CommonAspectRatio;
use crate::enums::common_resolution::CommonResolution;
use crate::enums::model_creator::ModelCreator;
use crate::enums::video_model::VideoModel;

const VEO_ASPECT_RATIOS: &[CommonAspectRatio] = &[
  CommonAspectRatio::Auto,
  CommonAspectRatio::WideSixteenByNine,
  CommonAspectRatio::TallNineBySixteen,
];

/// Google Veo video models.
pub fn veo_video_models() -> Vec<VideoModelConfig> {
  vec![
    VideoModelConfig {
      model: VideoModel::Veo3p1,
      model_creator: ModelCreator::Google,
      full_name: "Google Veo 3.1".to_string(),
      selector_name: "Google Veo 3.1".to_string(),
      selector_description: "Slow, high-quality model".to_string(),
      selector_badges: strings(&["2 min."]),
      progress_bar_ms: 100_000,
      text_prompt_max_length: Some(5000),
      starting_keyframe_supported: true,
      starting_keyframe_required: true,
      text_to_video_supported: false,
      ending_keyframe_supported: true,
      image_references_supported: true,
      image_references_max: Some(3),
      video_references_supported: true,
      video_references_max: Some(1),
      show_generate_with_sound_toggle: true,
      aspect_ratio_options: VEO_ASPECT_RATIOS.to_vec(),
      aspect_ratio_default: Some(CommonAspectRatio::WideSixteenByNine),
      resolution_options: vec![CommonResolution::SevenTwentyP, CommonResolution::TenEightyP, CommonResolution::FourK],
      resolution_default: Some(CommonResolution::TenEightyP),
      duration_seconds_min: Some(4),
      duration_seconds_max: Some(8),
      duration_seconds_default: Some(8),
      ..Default::default()
    },
    VideoModelConfig {
      model: VideoModel::Veo3p1Fast,
      model_creator: ModelCreator::Google,
      full_name: "Google Veo 3.1 Fast".to_string(),
      selector_name: "Google Veo 3.1 Fast".to_string(),
      selector_description: "High-quality model (faster)".to_string(),
      selector_badges: strings(&["2 min."]),
      progress_bar_ms: 100_000,
      text_prompt_max_length: Some(5000),
      starting_keyframe_supported: true,
      starting_keyframe_required: true,
      text_to_video_supported: false,
      ending_keyframe_supported: true,
      image_references_supported: true,
      image_references_max: Some(3),
      video_references_supported: true,
      video_references_max: Some(1),
      show_generate_with_sound_toggle: true,
      aspect_ratio_options: VEO_ASPECT_RATIOS.to_vec(),
      aspect_ratio_default: Some(CommonAspectRatio::WideSixteenByNine),
      resolution_options: vec![CommonResolution::SevenTwentyP, CommonResolution::TenEightyP, CommonResolution::FourK],
      resolution_default: Some(CommonResolution::TenEightyP),
      duration_seconds_min: Some(4),
      duration_seconds_max: Some(8),
      duration_seconds_default: Some(8),
      ..Default::default()
    },
    VideoModelConfig {
      model: VideoModel::Veo3p1Lite,
      model_creator: ModelCreator::Google,
      full_name: "Google Veo 3.1 Lite".to_string(),
      selector_name: "Google Veo 3.1 Lite".to_string(),
      selector_description: "Cheaper, lighter Veo".to_string(),
      selector_badges: strings(&["2 min."]),
      progress_bar_ms: 100_000,
      text_prompt_max_length: Some(5000),
      starting_keyframe_supported: true,
      ending_keyframe_supported: true,
      show_generate_with_sound_toggle: true,
      aspect_ratio_options: VEO_ASPECT_RATIOS.to_vec(),
      aspect_ratio_default: Some(CommonAspectRatio::WideSixteenByNine),
      resolution_options: vec![CommonResolution::SevenTwentyP, CommonResolution::TenEightyP],
      resolution_default: Some(CommonResolution::SevenTwentyP),
      duration_seconds_min: Some(4),
      duration_seconds_max: Some(8),
      duration_seconds_default: Some(8),
      ..Default::default()
    },
    VideoModelConfig {
      model: VideoModel::Veo3Fast,
      model_creator: ModelCreator::Google,
      full_name: "Google Veo 3 Fast".to_string(),
      selector_name: "Google Veo 3 Fast".to_string(),
      selector_description: "High-quality model (faster)".to_string(),
      selector_badges: strings(&["2 min."]),
      progress_bar_ms: 100_000,
      text_prompt_max_length: Some(5000),
      starting_keyframe_supported: true,
      starting_keyframe_required: true,
      text_to_video_supported: false,
      show_generate_with_sound_toggle: true,
      resolution_options: vec![CommonResolution::SevenTwentyP, CommonResolution::TenEightyP],
      resolution_default: Some(CommonResolution::TenEightyP),
      duration_seconds_min: Some(4),
      duration_seconds_max: Some(8),
      duration_seconds_default: Some(8),
      ..Default::default()
    },
    VideoModelConfig {
      model: VideoModel::Veo3,
      model_creator: ModelCreator::Google,
      full_name: "Google Veo 3".to_string(),
      selector_name: "Google Veo 3".to_string(),
      selector_description: "Slow, high-quality model".to_string(),
      selector_badges: strings(&["2 min."]),
      progress_bar_ms: 100_000,
      text_prompt_max_length: Some(5000),
      starting_keyframe_supported: true,
      starting_keyframe_required: true,
      text_to_video_supported: false,
      show_generate_with_sound_toggle: true,
      aspect_ratio_options: vec![CommonAspectRatio::WideSixteenByNine, CommonAspectRatio::TallNineBySixteen, CommonAspectRatio::Auto],
      aspect_ratio_default: Some(CommonAspectRatio::WideSixteenByNine),
      resolution_options: vec![CommonResolution::SevenTwentyP, CommonResolution::TenEightyP],
      resolution_default: Some(CommonResolution::TenEightyP),
      duration_seconds_min: Some(4),
      duration_seconds_max: Some(8),
      duration_seconds_default: Some(8),
      ..Default::default()
    },
    VideoModelConfig {
      model: VideoModel::Veo2,
      model_creator: ModelCreator::Google,
      full_name: "Google Veo 2".to_string(),
      selector_name: "Google Veo 2".to_string(),
      selector_description: "Fast video model".to_string(),
      selector_badges: strings(&["2 min."]),
      progress_bar_ms: 100_000,
      text_prompt_max_length: Some(5000),
      starting_keyframe_supported: true,
      starting_keyframe_required: true,
      text_to_video_supported: false,
      aspect_ratio_options: VEO_ASPECT_RATIOS.to_vec(),
      aspect_ratio_default: Some(CommonAspectRatio::WideSixteenByNine),
      duration_seconds_min: Some(5),
      duration_seconds_max: Some(8),
      duration_seconds_default: Some(5),
      ..Default::default()
    },
  ]
}
