//! The strongly-typed id types for entities that are NOT database rows
//! (credential files, and whatever comes next).
//!
//! Each is a transparent newtype over `String` generated by
//! [`define_id!`] (see `utils::id_core`), so it carries its prefix,
//! `generate()`s time-ordered ULIDs, and validates on `FromStr`. Passing a
//! `CredentialId` where another id is expected is a compile error — that is
//! the entire point. NEVER use bare `String` ids.
//!
//! Database identifiers live elsewhere: `sqlite_identifiers` for the local
//! tasks database, `artcraft_client::tokens` for the server API.

#[macro_use]
pub mod utils;

pub mod credential_id;

pub use credential_id::CredentialId;
pub use utils::id_core::ParseIdError;
