import { Object3DModel } from "../classes/Object3DModel.js";
import { ModelCreator } from "../classes/metadata/ModelCreator.js";
import { GenerationProvider } from "@storyteller/api-enums";

export const OBJECT_3D_MODELS: Object3DModel[] = [
  new Object3DModel({
    id: "hunyuan_3d_3",
    tauriId: "hunyuan_3d_3",
    fullName: "Hunyuan 3D 3.0",
    category: "3d_object",
    creator: ModelCreator.Tencent,
    selectorName: "Hunyuan 3.0",
    selectorDescription: "Highest quality 3D mesh generation",
    selectorBadges: ["~2 min."],
    providers: [GenerationProvider.Artcraft],
    progressBarTime: 120000,
  }),
  new Object3DModel({
    id: "hunyuan_3d_3p1_pro",
    tauriId: "hunyuan_3d_3p1_pro",
    fullName: "Hunyuan 3D 3.1 Pro",
    category: "3d_object",
    creator: ModelCreator.Tencent,
    selectorName: "Hunyuan 3.1 Pro",
    selectorDescription: "Newest Hunyuan, highest quality",
    selectorBadges: ["~2 min."],
    providers: [GenerationProvider.Artcraft],
    progressBarTime: 120000,
  }),
  new Object3DModel({
    id: "hunyuan_3d_3p1_rapid",
    tauriId: "hunyuan_3d_3p1_rapid",
    fullName: "Hunyuan 3D 3.1 Rapid",
    category: "3d_object",
    creator: ModelCreator.Tencent,
    selectorName: "Hunyuan 3.1 Rapid",
    selectorDescription: "Newest Hunyuan, fast",
    selectorBadges: ["~1 min."],
    providers: [GenerationProvider.Artcraft],
    progressBarTime: 60000,
  }),
  new Object3DModel({
    id: "hunyuan_3d_2p1",
    tauriId: "hunyuan_3d_2p1",
    fullName: "Hunyuan 3D 2.1",
    category: "3d_object",
    creator: ModelCreator.Tencent,
    selectorName: "Hunyuan 2.1",
    selectorDescription: "Faster, lower fidelity 3D mesh",
    selectorBadges: ["~45 sec."],
    providers: [GenerationProvider.Artcraft],
    progressBarTime: 60000,
  }),
  new Object3DModel({
    id: "hunyuan_3d_2p0",
    tauriId: "hunyuan_3d_2p0",
    fullName: "Hunyuan 3D 2.0",
    category: "3d_object",
    creator: ModelCreator.Tencent,
    selectorName: "Hunyuan 2.0",
    selectorDescription: "Faster, lower fidelity 3D mesh",
    selectorBadges: ["~45 sec."],
    providers: [GenerationProvider.Artcraft],
    progressBarTime: 60000,
  }),
  new Object3DModel({
    id: "tripo3d_h3p1",
    tauriId: "tripo3d_h3p1",
    fullName: "Tripo3D H3.1",
    category: "3d_object",
    creator: ModelCreator.Tripo,
    selectorName: "Tripo3D H3.1",
    selectorDescription: "High quality with texture controls",
    selectorBadges: ["~2 min."],
    providers: [GenerationProvider.Artcraft],
    progressBarTime: 120000,
  }),
  new Object3DModel({
    id: "meshy_v6",
    tauriId: "meshy_v6",
    fullName: "Meshy 6",
    category: "3d_object",
    creator: ModelCreator.Meshy,
    selectorName: "Meshy 6",
    selectorDescription: "High quality with low-poly output",
    selectorBadges: ["~2 min."],
    providers: [GenerationProvider.Artcraft],
    progressBarTime: 120000,
  }),
  new Object3DModel({
    id: "rodin_2p5_fast",
    tauriId: "rodin_2p5_fast",
    fullName: "Rodin 2.5 Fast",
    category: "3d_object",
    creator: ModelCreator.Deemos,
    selectorName: "Rodin 2.5 Fast",
    selectorDescription: "Fast, inexpensive 3D mesh",
    selectorBadges: ["~1 min."],
    providers: [GenerationProvider.Artcraft],
    progressBarTime: 60000,
  }),
];

export const OBJECT_3D_MODELS_BY_ID: Map<string, Object3DModel> = new Map(
  OBJECT_3D_MODELS.map((model) => [model.id, model]),
);

if (OBJECT_3D_MODELS_BY_ID.size !== OBJECT_3D_MODELS.length) {
  throw new Error("All 3D object models must have unique IDs");
}
