import { GenerationProvider } from "@storyteller/api-enums";
import { VideoModel } from "../classes/VideoModel.js";
import { ModelCreator } from "../classes/metadata/ModelCreator.js";
import { SizeIconOption } from "../classes/metadata/SizeOption.js";

export const VIDEO_MODELS: VideoModel[] = [
  new VideoModel({
    id: "grok_video",
    tauriId: "grok_imagine_video",
    fullName: "Grok Video",
    category: "video",
    creator: ModelCreator.Grok,
    providers: [GenerationProvider.Grok],
    selectorName: "Grok Video",
    selectorDescription: "Fastest video model",
    selectorBadges: ["20 sec."],
    startFrame: true,
    endFrame: false,
    requiresImage: true,
    progressBarTime: 50000,
    maxPromptLength: 4096,
    sizeOptions: [
      {
        tauriValue: "landscape",
        textLabel: "Landscape",
        icon: SizeIconOption.Landscape,
      },
      {
        tauriValue: "portrait",
        textLabel: "Portrait",
        icon: SizeIconOption.Portrait,
      },
      {
        tauriValue: "square",
        textLabel: "Square",
        icon: SizeIconOption.Square,
      },
    ],
  }),
  new VideoModel({
    id: "grok_imagine_video_1p5",
    tauriId: "grok_imagine_video_1p5",
    fullName: "Grok Imagine 1.5",
    category: "video",
    creator: ModelCreator.Grok,
    // Served via Artcraft (storyteller-web / artcraft_router) for now, even
    // though the model is made by xAI. See generate_video_command.rs.
    providers: [GenerationProvider.Artcraft],
    selectorName: "Grok Imagine 1.5",
    selectorDescription: "Image-to-video by xAI",
    selectorBadges: ["Preview"],
    startFrame: true,
    endFrame: false,
    requiresImage: true,
    textToVideoSupported: false,
    progressBarTime: 50000,
    maxPromptLength: 4096,
    resolutionOptions: ["480p", "720p"],
    defaultResolution: "720p",
    sizeOptions: [
      {
        tauriValue: "landscape",
        textLabel: "Landscape",
        icon: SizeIconOption.Landscape,
      },
      {
        tauriValue: "portrait",
        textLabel: "Portrait",
        icon: SizeIconOption.Portrait,
      },
      {
        tauriValue: "square",
        textLabel: "Square",
        icon: SizeIconOption.Square,
      },
    ],
  }),
  new VideoModel({
    id: "kling_1_6_pro",
    tauriId: "kling_1p6_pro",
    fullName: "Kling 1.6 Pro",
    category: "video",
    creator: ModelCreator.Kling,
    selectorName: "Kling 1.6 Pro",
    selectorDescription: "Fast video model",
    selectorBadges: ["2 min."],
    startFrame: true,
    endFrame: true,
    requiresImage: true,
    progressBarTime: 300000,
    maxPromptLength: 2500,
    generateWithSound: false,
  }),
  new VideoModel({
    id: "kling_2_1_pro",
    tauriId: "kling_2p1_pro",
    fullName: "Kling 2.1 Pro",
    category: "video",
    creator: ModelCreator.Kling,
    selectorName: "Kling 2.1 Pro",
    selectorDescription: "Fast video model",
    selectorBadges: ["2 min."],
    startFrame: true,
    endFrame: true,
    requiresImage: true,
    progressBarTime: 300000,
    maxPromptLength: 2500,
    generateWithSound: false,
  }),
  new VideoModel({
    id: "kling_2_1_master",
    tauriId: "kling_2p1_master",
    fullName: "Kling 2.1 Master",
    category: "video",
    creator: ModelCreator.Kling,
    selectorName: "Kling 2.1 Master",
    selectorDescription: "Fast video model",
    selectorBadges: ["2 min."],
    startFrame: true,
    endFrame: false,
    requiresImage: true,
    progressBarTime: 300000,
    maxPromptLength: 2500,
    generateWithSound: false,
  }),
  new VideoModel({
    id: "kling_2p5_turbo_pro",
    tauriId: "kling_2p5_turbo_pro",
    fullName: "Kling 2.5 Turbo Pro",
    category: "video",
    creator: ModelCreator.Kling,
    selectorName: "Kling 2.5 Turbo Pro",
    selectorDescription: "Fast video model",
    selectorBadges: ["2 min."],
    startFrame: true,
    endFrame: true,
    requiresImage: false,
    progressBarTime: 300000,
    maxPromptLength: 2500,
    generateWithSound: false,
  }),
  new VideoModel({
    id: "kling_2p6_pro",
    tauriId: "kling_2p6_pro",
    fullName: "Kling 2.6 Pro",
    category: "video",
    creator: ModelCreator.Kling,
    selectorName: "Kling 2.6 Pro",
    selectorDescription: "Fast video model",
    selectorBadges: ["2 min."],
    startFrame: true,
    endFrame: false,
    requiresImage: true,
    progressBarTime: 300000,
    maxPromptLength: 2500,
    generateWithSound: false,
  }),
  new VideoModel({
    id: "kling_3p0_standard",
    tauriId: "kling_3p0_standard",
    fullName: "Kling 3.0 Standard",
    category: "video",
    creator: ModelCreator.Kling,
    selectorName: "Kling 3.0 Standard",
    selectorDescription: "Standard quality video model",
    selectorBadges: ["2 min."],
    startFrame: true,
    endFrame: true,
    requiresImage: false,
    sizeOptions: [
      {
        tauriValue: "wide_sixteen_by_nine",
        textLabel: "16:9",
        icon: SizeIconOption.Landscape16x9,
      },
      {
        tauriValue: "square",
        textLabel: "1:1",
        icon: SizeIconOption.Square,
      },
      {
        tauriValue: "tall_nine_by_sixteen",
        textLabel: "9:16",
        icon: SizeIconOption.Portrait9x16,
      },
    ],
    supportsCommonAspectRatio: true,
    durationOptions: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    defaultDuration: 5,
    progressBarTime: 300000,
    maxPromptLength: 2500,
    generateWithSound: true,
  }),
  new VideoModel({
    id: "kling_3p0_pro",
    tauriId: "kling_3p0_pro",
    fullName: "Kling 3.0 Pro",
    category: "video",
    creator: ModelCreator.Kling,
    selectorName: "Kling 3.0 Pro",
    selectorDescription: "High quality video model",
    selectorBadges: ["2 min."],
    startFrame: true,
    endFrame: true,
    requiresImage: false,
    sizeOptions: [
      {
        tauriValue: "wide_sixteen_by_nine",
        textLabel: "16:9",
        icon: SizeIconOption.Landscape16x9,
      },
      {
        tauriValue: "square",
        textLabel: "1:1",
        icon: SizeIconOption.Square,
      },
      {
        tauriValue: "tall_nine_by_sixteen",
        textLabel: "9:16",
        icon: SizeIconOption.Portrait9x16,
      },
    ],
    supportsCommonAspectRatio: true,
    durationOptions: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    defaultDuration: 5,
    progressBarTime: 300000,
    maxPromptLength: 2500,
    generateWithSound: true,
  }),
  new VideoModel({
    id: "happy_horse_1p0",
    tauriId: "happy_horse_1p0",
    fullName: "Happy Horse 1.0",
    category: "video",
    creator: ModelCreator.Alibaba,
    selectorName: "Happy Horse 1.0",
    selectorDescription: "High quality video model",
    selectorBadges: ["2 min."],
    startFrame: true,
    endFrame: false,
    requiresImage: false,
    resolutionOptions: ["720p", "1080p"],
    sizeOptions: [
      {
        tauriValue: "wide_sixteen_by_nine",
        textLabel: "16:9",
        icon: SizeIconOption.Landscape16x9,
      },
      {
        tauriValue: "wide_four_by_three",
        textLabel: "4:3",
        icon: SizeIconOption.Standard4x3,
      },
      {
        tauriValue: "square",
        textLabel: "1:1",
        icon: SizeIconOption.Square,
      },
      {
        tauriValue: "tall_three_by_four",
        textLabel: "3:4",
        icon: SizeIconOption.Portrait3x4,
      },
      {
        tauriValue: "tall_nine_by_sixteen",
        textLabel: "9:16",
        icon: SizeIconOption.Portrait9x16,
      },
    ],
    supportsCommonAspectRatio: true,
    durationOptions: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    defaultDuration: 5,
    progressBarTime: 300000,
    maxPromptLength: 2500,
    generateWithSound: true,
  }),
  new VideoModel({
    id: "seedance_1_0_lite",
    tauriId: "seedance_1p0_lite",
    fullName: "Seedance 1.0 Lite",
    category: "video",
    creator: ModelCreator.Bytedance,
    selectorName: "Seedance 1.0 Lite",
    selectorDescription: "Fast video model",
    selectorBadges: ["2 min."],
    startFrame: true,
    endFrame: false,
    requiresImage: true,
    progressBarTime: 100000,
    maxPromptLength: 3000,
  }),
  new VideoModel({
    id: "seedance_1p5_pro",
    tauriId: "seedance_1p5_pro",
    fullName: "Seedance 1.5 Pro",
    category: "video",
    creator: ModelCreator.Bytedance,
    selectorName: "Seedance 1.5 Pro",
    selectorDescription: "High quality video model",
    selectorBadges: ["2 min."],
    startFrame: true,
    endFrame: true,
    requiresImage: false,
    sizeOptions: [
      {
        tauriValue: "wide_sixteen_by_nine",
        textLabel: "16:9",
        icon: SizeIconOption.Landscape16x9,
      },
      {
        tauriValue: "square",
        textLabel: "1:1",
        icon: SizeIconOption.Square,
      },
      {
        tauriValue: "tall_three_by_four",
        textLabel: "3:4",
        icon: SizeIconOption.Portrait3x4,
      },
      {
        tauriValue: "wide_four_by_three",
        textLabel: "4:3",
        icon: SizeIconOption.Standard4x3,
      },
      {
        tauriValue: "tall_nine_by_sixteen",
        textLabel: "9:16",
        icon: SizeIconOption.Portrait9x16,
      },
      {
        tauriValue: "wide_twenty_one_by_nine",
        textLabel: "21:9",
        icon: SizeIconOption.Landscape,
      },
    ],
    durationOptions: [4, 5, 6, 7, 8, 9, 10, 11, 12],
    defaultDuration: 5,
    resolutionOptions: ["480p", "720p", "1080p"],
    defaultResolution: "720p",
    supportsSystemPrompt: false,
    generateWithSound: true,
    progressBarTime: 180000,
    maxPromptLength: 3000,
  }),
  new VideoModel({
    id: "seedance_2p0",
    tauriId: "seedance_2p0",
    fullName: "Seedance 2.0",
    category: "video",
    creator: ModelCreator.Bytedance,
    selectorName: "Seedance 2.0",
    selectorDescription: "High quality model",
    selectorBadges: ["~15 min."],
    startFrame: true,
    endFrame: true,
    requiresImage: false,
    sizeOptions: [
      {
        tauriValue: "wide_twenty_one_by_nine",
        textLabel: "21:9",
        icon: SizeIconOption.Landscape16x9,
      },
      {
        tauriValue: "wide_sixteen_by_nine",
        textLabel: "16:9",
        icon: SizeIconOption.Landscape16x9,
      },
      {
        tauriValue: "square",
        textLabel: "1:1",
        icon: SizeIconOption.Square,
      },
      {
        tauriValue: "tall_three_by_four",
        textLabel: "3:4",
        icon: SizeIconOption.Portrait3x4,
      },
      {
        tauriValue: "wide_four_by_three",
        textLabel: "4:3",
        icon: SizeIconOption.Standard4x3,
      },
      {
        tauriValue: "tall_nine_by_sixteen",
        textLabel: "9:16",
        icon: SizeIconOption.Portrait9x16,
      },
    ],
    supportsCommonAspectRatio: true,
    durationOptions: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    defaultDuration: 5,
    supportsReferenceMode: true,
    maxReferenceImages: 9,
    maxReferenceVideos: 3,
    maxVideoRefDuration: 15,
    maxReferenceAudios: 3,
    maxAudioRefDuration: 15,
    resolutionOptions: ["480p", "720p", "1080p"],
    defaultResolution: "720p",
    supportsSystemPrompt: false,
    progressBarTime: 900000, // ~15 minutes
    maxPromptLength: Infinity,
  }),
  new VideoModel({
    id: "seedance_2p0_fast",
    tauriId: "seedance_2p0_fast",
    fullName: "Seedance 2.0 Fast",
    category: "video",
    creator: ModelCreator.Bytedance,
    selectorName: "Seedance 2.0 Fast",
    selectorDescription: "Fast and high quality",
    selectorBadges: ["~5 min."],
    startFrame: true,
    endFrame: true,
    requiresImage: false,
    sizeOptions: [
      {
        tauriValue: "wide_twenty_one_by_nine",
        textLabel: "21:9",
        icon: SizeIconOption.Landscape16x9,
      },
      {
        tauriValue: "wide_sixteen_by_nine",
        textLabel: "16:9",
        icon: SizeIconOption.Landscape16x9,
      },
      {
        tauriValue: "square",
        textLabel: "1:1",
        icon: SizeIconOption.Square,
      },
      {
        tauriValue: "tall_three_by_four",
        textLabel: "3:4",
        icon: SizeIconOption.Portrait3x4,
      },
      {
        tauriValue: "wide_four_by_three",
        textLabel: "4:3",
        icon: SizeIconOption.Standard4x3,
      },
      {
        tauriValue: "tall_nine_by_sixteen",
        textLabel: "9:16",
        icon: SizeIconOption.Portrait9x16,
      },
    ],
    supportsCommonAspectRatio: true,
    durationOptions: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    defaultDuration: 5,
    supportsReferenceMode: true,
    maxReferenceImages: 9,
    maxReferenceVideos: 3,
    maxVideoRefDuration: 15,
    maxReferenceAudios: 3,
    maxAudioRefDuration: 15,
    resolutionOptions: ["480p", "720p"],
    defaultResolution: "720p",
    supportsSystemPrompt: false,
    progressBarTime: 300000, // ~5 minutes
    maxPromptLength: Infinity,
  }),
  new VideoModel({
    id: "sora_2",
    tauriId: "sora_2",
    fullName: "Sora 2",
    category: "video",
    creator: ModelCreator.OpenAi,
    providers: [GenerationProvider.Artcraft, GenerationProvider.Sora],
    selectorName: "Sora 2",
    selectorDescription: "Smart video model",
    selectorBadges: ["2 min."],
    startFrame: false,
    endFrame: false,
    requiresImage: false,
    sizeOptions: [
      {
        tauriValue: "landscape",
        textLabel: "Landscape",
        icon: SizeIconOption.Landscape,
      },
      {
        tauriValue: "portrait",
        textLabel: "Portrait",
        icon: SizeIconOption.Portrait,
      },
    ],
    progressBarTime: 100000,
    maxPromptLength: 2000,
  }),
  new VideoModel({
    id: "sora_2_pro",
    tauriId: "sora_2_pro",
    fullName: "Sora 2 Pro",
    category: "video",
    creator: ModelCreator.OpenAi,
    selectorName: "Sora 2 Pro",
    selectorDescription: "Smart video model",
    selectorBadges: ["2 min."],
    startFrame: false,
    endFrame: false,
    requiresImage: false,
    sizeOptions: [
      {
        tauriValue: "landscape",
        textLabel: "Landscape",
        icon: SizeIconOption.Landscape,
      },
      {
        tauriValue: "portrait",
        textLabel: "Portrait",
        icon: SizeIconOption.Portrait,
      },
    ],
    progressBarTime: 100000,
    maxPromptLength: 2000,
  }),
  new VideoModel({
    id: "veo_2",
    tauriId: "veo_2",
    fullName: "Google Veo 2",
    category: "video",
    creator: ModelCreator.Google,
    selectorName: "Google Veo 2",
    selectorDescription: "Fast video model",
    selectorBadges: ["2 min."],
    startFrame: true,
    endFrame: false,
    requiresImage: true,
    generateWithSound: false,
    progressBarTime: 100000,
    maxPromptLength: 5000,
  }),
  new VideoModel({
    id: "veo_3",
    tauriId: "veo_3",
    fullName: "Google Veo 3",
    category: "video",
    creator: ModelCreator.Google,
    selectorName: "Google Veo 3",
    selectorDescription: "Slow, high-quality model",
    selectorBadges: ["2 min."],
    startFrame: true,
    endFrame: false,
    requiresImage: true,
    generateWithSound: true,
    progressBarTime: 100000,
    maxPromptLength: 5000,
  }),
  new VideoModel({
    id: "veo_3_fast",
    tauriId: "veo_3_fast",
    fullName: "Google Veo 3 Fast",
    category: "video",
    creator: ModelCreator.Google,
    selectorName: "Google Veo 3 Fast",
    selectorDescription: "High-quality model (faster)",
    selectorBadges: ["2 min."],
    startFrame: true,
    endFrame: false,
    requiresImage: true,
    generateWithSound: true,
    progressBarTime: 100000,
    maxPromptLength: 5000,
  }),
  new VideoModel({
    id: "veo_3p1",
    tauriId: "veo_3p1",
    fullName: "Google Veo 3.1",
    category: "video",
    creator: ModelCreator.Google,
    selectorName: "Google Veo 3.1",
    selectorDescription: "Slow, high-quality model",
    selectorBadges: ["2 min."],
    startFrame: true,
    endFrame: false,
    requiresImage: true,
    generateWithSound: true,
    progressBarTime: 100000,
    maxPromptLength: 5000,
  }),
  new VideoModel({
    id: "veo_3p1_fast",
    tauriId: "veo_3p1_fast",
    fullName: "Google Veo 3.1 Fast",
    category: "video",
    creator: ModelCreator.Google,
    selectorName: "Google Veo 3.1 Fast",
    selectorDescription: "High-quality model (faster)",
    selectorBadges: ["2 min."],
    startFrame: true,
    endFrame: false,
    requiresImage: true,
    generateWithSound: true,
    progressBarTime: 100000,
    maxPromptLength: 5000,
  }),
  new VideoModel({
    id: "switch_x",
    tauriId: "switch_x",
    fullName: "Beeble SwitchX",
    category: "video",
    creator: ModelCreator.Beeble,
    selectorName: "Beeble SwitchX",
    selectorDescription: "Relight, change location, swap objects.",
    selectorBadges: ["5 min."],
    startFrame: false,
    endFrame: false,
    requiresImage: true,
    progressBarTime: 5 * 60 * 1000,
    maxPromptLength: 2000,
  }),
];

export const VIDEO_MODELS_BY_ID: Map<string, VideoModel> = new Map(
  VIDEO_MODELS.map((model) => [model.id, model]),
);

if (VIDEO_MODELS_BY_ID.size !== VIDEO_MODELS.length) {
  throw new Error("All video models must have unique IDs");
}
