[package]
name = "identifiers"
edition = "2021"
version = "0.0.1"
authors = [
    "Brandon Thomas <bt@brand.io>",
    "Brandon Thomas <echelon@gmail.com>",
]
publish = false

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-build-acceleration"]

[lib]
name = "identifiers"
path = "src/lib.rs"

[dependencies]
# Workspace hack (faster compile times)
workspace-build-acceleration.workspace = true

# Serialization (define_id! expansion references ::serde)
serde.workspace = true

# Id entropy (time-ordered ULIDs)
ulid = "1"

[dev-dependencies]
# Test serialization
serde_json.workspace = true
